spring:
  application:
    name: Humo_Online_Jobs

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: b1t
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5